<?php $icons = array();
$icons['icomoon-brankic-32x32']['number'] = array("class"=>'number',"tags"=>'number,one',"unicode"=>'');
$icons['icomoon-brankic-32x32']['number2'] = array("class"=>'number2',"tags"=>'number,two',"unicode"=>'');
$icons['icomoon-brankic-32x32']['number3'] = array("class"=>'number3',"tags"=>'number,three',"unicode"=>'');
$icons['icomoon-brankic-32x32']['number4'] = array("class"=>'number4',"tags"=>'number,four',"unicode"=>'');
$icons['icomoon-brankic-32x32']['number5'] = array("class"=>'number5',"tags"=>'number,five',"unicode"=>'');
$icons['icomoon-brankic-32x32']['number6'] = array("class"=>'number6',"tags"=>'number,six',"unicode"=>'');
$icons['icomoon-brankic-32x32']['number7'] = array("class"=>'number7',"tags"=>'number,seven',"unicode"=>'');
$icons['icomoon-brankic-32x32']['number8'] = array("class"=>'number8',"tags"=>'number,eight',"unicode"=>'');
$icons['icomoon-brankic-32x32']['number9'] = array("class"=>'number9',"tags"=>'number,nine',"unicode"=>'');
$icons['icomoon-brankic-32x32']['number10'] = array("class"=>'number10',"tags"=>'number,zero',"unicode"=>'');
$icons['icomoon-brankic-32x32']['number11'] = array("class"=>'number11',"tags"=>'number,one',"unicode"=>'');
$icons['icomoon-brankic-32x32']['number12'] = array("class"=>'number12',"tags"=>'number,two',"unicode"=>'');
$icons['icomoon-brankic-32x32']['number13'] = array("class"=>'number13',"tags"=>'number,three',"unicode"=>'');
$icons['icomoon-brankic-32x32']['number14'] = array("class"=>'number14',"tags"=>'number,four',"unicode"=>'');
$icons['icomoon-brankic-32x32']['number15'] = array("class"=>'number15',"tags"=>'number,five',"unicode"=>'');
$icons['icomoon-brankic-32x32']['number16'] = array("class"=>'number16',"tags"=>'number,six',"unicode"=>'');
$icons['icomoon-brankic-32x32']['number17'] = array("class"=>'number17',"tags"=>'number,seven',"unicode"=>'');
$icons['icomoon-brankic-32x32']['number18'] = array("class"=>'number18',"tags"=>'number,eight',"unicode"=>'');
$icons['icomoon-brankic-32x32']['number19'] = array("class"=>'number19',"tags"=>'number,nine',"unicode"=>'');
$icons['icomoon-brankic-32x32']['number20'] = array("class"=>'number20',"tags"=>'number,zero',"unicode"=>'');
$icons['icomoon-brankic-32x32']['quote'] = array("class"=>'quote',"tags"=>'quote,rdquo',"unicode"=>'');
$icons['icomoon-brankic-32x32']['quote2'] = array("class"=>'quote2',"tags"=>'quote,rdquo',"unicode"=>'');
$icons['icomoon-brankic-32x32']['tag'] = array("class"=>'tag',"tags"=>'tag,price',"unicode"=>'');
$icons['icomoon-brankic-32x32']['tag2'] = array("class"=>'tag2',"tags"=>'tag,price',"unicode"=>'');
$icons['icomoon-brankic-32x32']['link'] = array("class"=>'link',"tags"=>'link,anchor,chain',"unicode"=>'');
$icons['icomoon-brankic-32x32']['link2'] = array("class"=>'link2',"tags"=>'link,anchor,chain',"unicode"=>'');
$icons['icomoon-brankic-32x32']['cabinet'] = array("class"=>'cabinet',"tags"=>'cabinet,drawer,storage',"unicode"=>'');
$icons['icomoon-brankic-32x32']['cabinet2'] = array("class"=>'cabinet2',"tags"=>'cabinet,drawer,storage',"unicode"=>'');
$icons['icomoon-brankic-32x32']['calendar'] = array("class"=>'calendar',"tags"=>'calendar,date,schedule',"unicode"=>'');
$icons['icomoon-brankic-32x32']['calendar2'] = array("class"=>'calendar2',"tags"=>'calendar,date,schedule',"unicode"=>'');
$icons['icomoon-brankic-32x32']['calendar3'] = array("class"=>'calendar3',"tags"=>'calendar,date,schedule',"unicode"=>'');
$icons['icomoon-brankic-32x32']['file'] = array("class"=>'file',"tags"=>'file,new,add',"unicode"=>'');
$icons['icomoon-brankic-32x32']['file2'] = array("class"=>'file2',"tags"=>'file,remove',"unicode"=>'');
$icons['icomoon-brankic-32x32']['file3'] = array("class"=>'file3',"tags"=>'file,list',"unicode"=>'');
$icons['icomoon-brankic-32x32']['files'] = array("class"=>'files',"tags"=>'files,stack,papers',"unicode"=>'');
$icons['icomoon-brankic-32x32']['phone'] = array("class"=>'phone',"tags"=>'phone,cellular phone,mobile',"unicode"=>'');
$icons['icomoon-brankic-32x32']['tablet'] = array("class"=>'tablet',"tags"=>'tablet,phone',"unicode"=>'');
$icons['icomoon-brankic-32x32']['window'] = array("class"=>'window',"tags"=>'window,desktop,program',"unicode"=>'');
$icons['icomoon-brankic-32x32']['monitor'] = array("class"=>'monitor',"tags"=>'monitor,pc,desktop,screen',"unicode"=>'');
$icons['icomoon-brankic-32x32']['ipod'] = array("class"=>'ipod',"tags"=>'ipod,music',"unicode"=>'');
$icons['icomoon-brankic-32x32']['tv'] = array("class"=>'tv',"tags"=>'tv,television,tube',"unicode"=>'');
$icons['icomoon-brankic-32x32']['camera'] = array("class"=>'camera',"tags"=>'camera,pictures,photos,images',"unicode"=>'');
$icons['icomoon-brankic-32x32']['camera2'] = array("class"=>'camera2',"tags"=>'camera,pictures,photos,images',"unicode"=>'');
$icons['icomoon-brankic-32x32']['camera3'] = array("class"=>'camera3',"tags"=>'camera,movie,video,record,film',"unicode"=>'');
$icons['icomoon-brankic-32x32']['film'] = array("class"=>'film',"tags"=>'film,movie,video',"unicode"=>'');
$icons['icomoon-brankic-32x32']['film2'] = array("class"=>'film2',"tags"=>'film,video,movie',"unicode"=>'');
$icons['icomoon-brankic-32x32']['film3'] = array("class"=>'film3',"tags"=>'film,photo',"unicode"=>'');
$icons['icomoon-brankic-32x32']['microphone'] = array("class"=>'microphone',"tags"=>'microphone,record,voice',"unicode"=>'');
$icons['icomoon-brankic-32x32']['microphone2'] = array("class"=>'microphone2',"tags"=>'microphone,record,voice',"unicode"=>'');
$icons['icomoon-brankic-32x32']['microphone3'] = array("class"=>'microphone3',"tags"=>'microphone,record,voice',"unicode"=>'');
$icons['icomoon-brankic-32x32']['drink'] = array("class"=>'drink',"tags"=>'drink,straw,glass',"unicode"=>'');
$icons['icomoon-brankic-32x32']['drink2'] = array("class"=>'drink2',"tags"=>'drink',"unicode"=>'');
$icons['icomoon-brankic-32x32']['drink3'] = array("class"=>'drink3',"tags"=>'drink',"unicode"=>'');
$icons['icomoon-brankic-32x32']['drink4'] = array("class"=>'drink4',"tags"=>'drink',"unicode"=>'');
$icons['icomoon-brankic-32x32']['coffee'] = array("class"=>'coffee',"tags"=>'coffee,cup,drink,break',"unicode"=>'');
$icons['icomoon-brankic-32x32']['mug'] = array("class"=>'mug',"tags"=>'mug,drink',"unicode"=>'');
$icons['icomoon-brankic-32x32']['icecream'] = array("class"=>'icecream',"tags"=>'ice cream,cone',"unicode"=>'');
$icons['icomoon-brankic-32x32']['cake'] = array("class"=>'cake',"tags"=>'cake,cup cake',"unicode"=>'');
$icons['icomoon-brankic-32x32']['inbox'] = array("class"=>'inbox',"tags"=>'inbox,archive,drawer',"unicode"=>'');
$icons['icomoon-brankic-32x32']['download'] = array("class"=>'download',"tags"=>'download,drawer,save,store,archive',"unicode"=>'');
$icons['icomoon-brankic-32x32']['upload'] = array("class"=>'upload',"tags"=>'upload,drawer,load',"unicode"=>'');
$icons['icomoon-brankic-32x32']['inbox2'] = array("class"=>'inbox2',"tags"=>'inbox,archive,drawer',"unicode"=>'');
$icons['icomoon-brankic-32x32']['checkmark'] = array("class"=>'checkmark',"tags"=>'checkmark,tick',"unicode"=>'');
$icons['icomoon-brankic-32x32']['checkmark2'] = array("class"=>'checkmark2',"tags"=>'checkmark,tick',"unicode"=>'');
$icons['icomoon-brankic-32x32']['cancel'] = array("class"=>'cancel',"tags"=>'cancel,close',"unicode"=>'');
$icons['icomoon-brankic-32x32']['cancel2'] = array("class"=>'cancel2',"tags"=>'cancel,close',"unicode"=>'');
$icons['icomoon-brankic-32x32']['plus'] = array("class"=>'plus',"tags"=>'plus,add',"unicode"=>'');
$icons['icomoon-brankic-32x32']['plus2'] = array("class"=>'plus2',"tags"=>'plus,add',"unicode"=>'');
$icons['icomoon-brankic-32x32']['minus'] = array("class"=>'minus',"tags"=>'minus,remove,delete',"unicode"=>'');
$icons['icomoon-brankic-32x32']['minus2'] = array("class"=>'minus2',"tags"=>'minus,remove,delete',"unicode"=>'');
$icons['icomoon-brankic-32x32']['notice'] = array("class"=>'notice',"tags"=>'notice,warning,explanation mark,notification',"unicode"=>'');
$icons['icomoon-brankic-32x32']['notice2'] = array("class"=>'notice2',"tags"=>'notice,warning,explanation mark,notification',"unicode"=>'');
$icons['icomoon-brankic-32x32']['cog'] = array("class"=>'cog',"tags"=>'cog,gear,settings,options',"unicode"=>'');
$icons['icomoon-brankic-32x32']['cogs'] = array("class"=>'cogs',"tags"=>'cogs,settings,gears,options,generate',"unicode"=>'');
$icons['icomoon-brankic-32x32']['cog2'] = array("class"=>'cog2',"tags"=>'cog,gear,settings,options',"unicode"=>'');
$icons['icomoon-brankic-32x32']['warning'] = array("class"=>'warning',"tags"=>'warning,notice,note',"unicode"=>'');
$icons['icomoon-brankic-32x32']['health'] = array("class"=>'health',"tags"=>'health,emergency,medicine',"unicode"=>'');
$icons['icomoon-brankic-32x32']['suitcase'] = array("class"=>'suitcase',"tags"=>'suitcase,briefcase',"unicode"=>'');
$icons['icomoon-brankic-32x32']['suitcase2'] = array("class"=>'suitcase2',"tags"=>'suitcase,briefcase',"unicode"=>'');
$icons['icomoon-brankic-32x32']['suitcase3'] = array("class"=>'suitcase3',"tags"=>'suitcase,briefcase',"unicode"=>'');
$icons['icomoon-brankic-32x32']['picture'] = array("class"=>'picture',"tags"=>'picture,images,photos,polaroid',"unicode"=>'');
$icons['icomoon-brankic-32x32']['pictures'] = array("class"=>'pictures',"tags"=>'pictures,images,photos,polaroid',"unicode"=>'');
$icons['icomoon-brankic-32x32']['pictures2'] = array("class"=>'pictures2',"tags"=>'pictures,images,photos,polaroid',"unicode"=>'');
$icons['icomoon-brankic-32x32']['android'] = array("class"=>'android',"tags"=>'android',"unicode"=>'');
$icons['icomoon-brankic-32x32']['marvin'] = array("class"=>'marvin',"tags"=>'marvin',"unicode"=>'');
$icons['icomoon-brankic-32x32']['pacman'] = array("class"=>'pacman',"tags"=>'pacman,game',"unicode"=>'');
$icons['icomoon-brankic-32x32']['cassette'] = array("class"=>'cassette',"tags"=>'cassette,audio,music,tape',"unicode"=>'');
$icons['icomoon-brankic-32x32']['watch'] = array("class"=>'watch',"tags"=>'watch,wrist watch,time,chronometer',"unicode"=>'');
$icons['icomoon-brankic-32x32']['chronometer'] = array("class"=>'chronometer',"tags"=>'chronometer,timer,clock',"unicode"=>'');
$icons['icomoon-brankic-32x32']['watch2'] = array("class"=>'watch2',"tags"=>'watch,time,wrist watch',"unicode"=>'');
$icons['icomoon-brankic-32x32']['alarmclock'] = array("class"=>'alarmclock',"tags"=>'alarm clock,time,notification',"unicode"=>'');
$icons['icomoon-brankic-32x32']['time'] = array("class"=>'time',"tags"=>'time,clock,alarm',"unicode"=>'');
$icons['icomoon-brankic-32x32']['time2'] = array("class"=>'time2',"tags"=>'time,clock',"unicode"=>'');
$icons['icomoon-brankic-32x32']['headphones'] = array("class"=>'headphones',"tags"=>'headphones,music,earphones',"unicode"=>'');
$icons['icomoon-brankic-32x32']['wallet'] = array("class"=>'wallet',"tags"=>'wallet,money',"unicode"=>'');
$icons['icomoon-brankic-32x32']['checkmark3'] = array("class"=>'checkmark3',"tags"=>'checkmark,tick,approve,submit',"unicode"=>'');
$icons['icomoon-brankic-32x32']['cancel3'] = array("class"=>'cancel3',"tags"=>'cancel,close,remove,dismiss',"unicode"=>'');
$icons['icomoon-brankic-32x32']['eye'] = array("class"=>'eye',"tags"=>'eye,views,vision',"unicode"=>'');
$icons['icomoon-brankic-32x32']['position'] = array("class"=>'position',"tags"=>'position,pin,map marker,marker',"unicode"=>'');
$icons['icomoon-brankic-32x32']['sitemap'] = array("class"=>'sitemap',"tags"=>'site map,tree,map',"unicode"=>'');
$icons['icomoon-brankic-32x32']['sitemap2'] = array("class"=>'sitemap2',"tags"=>'site map,tree,map',"unicode"=>'');
$icons['icomoon-brankic-32x32']['cloud'] = array("class"=>'cloud',"tags"=>'cloud,weather',"unicode"=>'');
$icons['icomoon-brankic-32x32']['upload2'] = array("class"=>'upload2',"tags"=>'upload,cloud',"unicode"=>'');
$icons['icomoon-brankic-32x32']['chart'] = array("class"=>'chart',"tags"=>'chart,pie,graph',"unicode"=>'');
$icons['icomoon-brankic-32x32']['chart2'] = array("class"=>'chart2',"tags"=>'chart,pie,graph',"unicode"=>'');
$icons['icomoon-brankic-32x32']['chart3'] = array("class"=>'chart3',"tags"=>'chart,bars,graph',"unicode"=>'');
$icons['icomoon-brankic-32x32']['chart4'] = array("class"=>'chart4',"tags"=>'chart,bars,graph',"unicode"=>'');
$icons['icomoon-brankic-32x32']['chart5'] = array("class"=>'chart5',"tags"=>'chart,bars,graph',"unicode"=>'');
$icons['icomoon-brankic-32x32']['chart6'] = array("class"=>'chart6',"tags"=>'chart,bars,graph',"unicode"=>'');
$icons['icomoon-brankic-32x32']['location'] = array("class"=>'location',"tags"=>'location,pin,map marker,marker',"unicode"=>'');
$icons['icomoon-brankic-32x32']['download2'] = array("class"=>'download2',"tags"=>'download,cloud',"unicode"=>'');
$icons['icomoon-brankic-32x32']['basket'] = array("class"=>'basket',"tags"=>'basket,shop,cart,ecommerce,buy,purchase',"unicode"=>'');
$icons['icomoon-brankic-32x32']['folder'] = array("class"=>'folder',"tags"=>'folder,directory,open,category',"unicode"=>'');
$icons['icomoon-brankic-32x32']['gamepad'] = array("class"=>'gamepad',"tags"=>'gamepad,joystick',"unicode"=>'');
$icons['icomoon-brankic-32x32']['alarm'] = array("class"=>'alarm',"tags"=>'alarm,bell,notification',"unicode"=>'');
$icons['icomoon-brankic-32x32']['alarm-cancel'] = array("class"=>'alarm-cancel',"tags"=>'alarm-cancel,bell,notification',"unicode"=>'');
$icons['icomoon-brankic-32x32']['phone2'] = array("class"=>'phone2',"tags"=>'phone,contact',"unicode"=>'');
$icons['icomoon-brankic-32x32']['phone3'] = array("class"=>'phone3',"tags"=>'phone,fax,contact,office',"unicode"=>'');
$icons['icomoon-brankic-32x32']['image'] = array("class"=>'image',"tags"=>'image,picture,photo,frame',"unicode"=>'');
$icons['icomoon-brankic-32x32']['open'] = array("class"=>'open',"tags"=>'open',"unicode"=>'');
$icons['icomoon-brankic-32x32']['sale'] = array("class"=>'sale',"tags"=>'sale',"unicode"=>'');
$icons['icomoon-brankic-32x32']['direction'] = array("class"=>'direction',"tags"=>'direction,address,location',"unicode"=>'');
$icons['icomoon-brankic-32x32']['map'] = array("class"=>'map',"tags"=>'map,location,address',"unicode"=>'');
$icons['icomoon-brankic-32x32']['trashcan'] = array("class"=>'trashcan',"tags"=>'trashcan,remove,delete',"unicode"=>'');
$icons['icomoon-brankic-32x32']['vote'] = array("class"=>'vote',"tags"=>'vote,election',"unicode"=>'');
$icons['icomoon-brankic-32x32']['graduate'] = array("class"=>'graduate',"tags"=>'graduate,hat',"unicode"=>'');
$icons['icomoon-brankic-32x32']['lab'] = array("class"=>'lab',"tags"=>'lab,beta,experiments',"unicode"=>'');
$icons['icomoon-brankic-32x32']['tie'] = array("class"=>'tie',"tags"=>'tie',"unicode"=>'');
$icons['icomoon-brankic-32x32']['football'] = array("class"=>'football',"tags"=>'football,sports,ball,rugby',"unicode"=>'');
$icons['icomoon-brankic-32x32']['eightball'] = array("class"=>'eightball',"tags"=>'eight ball,snooker,billiards,sports',"unicode"=>'');
$icons['icomoon-brankic-32x32']['bowling'] = array("class"=>'bowling',"tags"=>'bowling,ball,stports',"unicode"=>'');
$icons['icomoon-brankic-32x32']['bowlingpin'] = array("class"=>'bowlingpin',"tags"=>'bowling pin,pin,stports',"unicode"=>'');
$icons['icomoon-brankic-32x32']['baseball'] = array("class"=>'baseball',"tags"=>'baseball,ball,sports',"unicode"=>'');
$icons['icomoon-brankic-32x32']['soccer'] = array("class"=>'soccer',"tags"=>'soccer,ball,football,sports',"unicode"=>'');
$icons['icomoon-brankic-32x32']['3dglasses'] = array("class"=>'3dglasses',"tags"=>'3d glasses,glasses',"unicode"=>'');
$icons['icomoon-brankic-32x32']['microwave'] = array("class"=>'microwave',"tags"=>'microwave,oven,kitchen',"unicode"=>'');
$icons['icomoon-brankic-32x32']['refrigerator'] = array("class"=>'refrigerator',"tags"=>'refrigerator,kitchen',"unicode"=>'');
$icons['icomoon-brankic-32x32']['oven'] = array("class"=>'oven',"tags"=>'oven,kitchen',"unicode"=>'');
$icons['icomoon-brankic-32x32']['washingmachine'] = array("class"=>'washingmachine',"tags"=>'washing machine,kitchen',"unicode"=>'');
$icons['icomoon-brankic-32x32']['mouse'] = array("class"=>'mouse',"tags"=>'mouse,pc,computer',"unicode"=>'');
$icons['icomoon-brankic-32x32']['smiley'] = array("class"=>'smiley',"tags"=>'smiley,emoticon,happy',"unicode"=>'');
$icons['icomoon-brankic-32x32']['sad'] = array("class"=>'sad',"tags"=>'sad,smiley,emoticon',"unicode"=>'');
$icons['icomoon-brankic-32x32']['mute'] = array("class"=>'mute',"tags"=>'mute,emoticon,smiley',"unicode"=>'');
$icons['icomoon-brankic-32x32']['hand'] = array("class"=>'hand',"tags"=>'hand,accessibility',"unicode"=>'');
$icons['icomoon-brankic-32x32']['radio'] = array("class"=>'radio',"tags"=>'radio,broadcast,news',"unicode"=>'');
$icons['icomoon-brankic-32x32']['satellite'] = array("class"=>'satellite',"tags"=>'satellite,broadcast',"unicode"=>'');
$icons['icomoon-brankic-32x32']['medal'] = array("class"=>'medal',"tags"=>'medal,first,win',"unicode"=>'');
$icons['icomoon-brankic-32x32']['medal2'] = array("class"=>'medal2',"tags"=>'medal,first,win',"unicode"=>'');
$icons['icomoon-brankic-32x32']['switch'] = array("class"=>'switch',"tags"=>'switch,power,lights',"unicode"=>'');
$icons['icomoon-brankic-32x32']['key'] = array("class"=>'key',"tags"=>'key,login,log in,sign in,password,unlock',"unicode"=>'');
$icons['icomoon-brankic-32x32']['cord'] = array("class"=>'cord',"tags"=>'cord,power,cable',"unicode"=>'');
$icons['icomoon-brankic-32x32']['locked'] = array("class"=>'locked',"tags"=>'locked,secure',"unicode"=>'');
$icons['icomoon-brankic-32x32']['unlocked'] = array("class"=>'unlocked',"tags"=>'unlocked',"unicode"=>'');
$icons['icomoon-brankic-32x32']['locked2'] = array("class"=>'locked2',"tags"=>'locked,secure',"unicode"=>'');
$icons['icomoon-brankic-32x32']['unlocked2'] = array("class"=>'unlocked2',"tags"=>'unlocked',"unicode"=>'');
$icons['icomoon-brankic-32x32']['magnifier'] = array("class"=>'magnifier',"tags"=>'magnifier,search,lookup,find',"unicode"=>'');
$icons['icomoon-brankic-32x32']['zoomin'] = array("class"=>'zoomin',"tags"=>'zoom in,magnifier,enlarge',"unicode"=>'');
$icons['icomoon-brankic-32x32']['zoomout'] = array("class"=>'zoomout',"tags"=>'zoom out,magnifier',"unicode"=>'');
$icons['icomoon-brankic-32x32']['stack'] = array("class"=>'stack',"tags"=>'stack,papers',"unicode"=>'');
$icons['icomoon-brankic-32x32']['stack2'] = array("class"=>'stack2',"tags"=>'stack,papers',"unicode"=>'');
$icons['icomoon-brankic-32x32']['stack3'] = array("class"=>'stack3',"tags"=>'stack',"unicode"=>'');
$icons['icomoon-brankic-32x32']['davidstar'] = array("class"=>'davidstar',"tags"=>'david star',"unicode"=>'');
$icons['icomoon-brankic-32x32']['cross'] = array("class"=>'cross',"tags"=>'cross',"unicode"=>'');
$icons['icomoon-brankic-32x32']['moonandstar'] = array("class"=>'moonandstar',"tags"=>'moon and star',"unicode"=>'');
$icons['icomoon-brankic-32x32']['transformers'] = array("class"=>'transformers',"tags"=>'transformers',"unicode"=>'');
$icons['icomoon-brankic-32x32']['batman'] = array("class"=>'batman',"tags"=>'batman',"unicode"=>'');
$icons['icomoon-brankic-32x32']['spaceinvaders'] = array("class"=>'spaceinvaders',"tags"=>'space invaders',"unicode"=>'');
$icons['icomoon-brankic-32x32']['skeletor'] = array("class"=>'skeletor',"tags"=>'skeletor',"unicode"=>'');
$icons['icomoon-brankic-32x32']['lamp'] = array("class"=>'lamp',"tags"=>'lamp,light',"unicode"=>'');
$icons['icomoon-brankic-32x32']['lamp2'] = array("class"=>'lamp2',"tags"=>'lamp,light',"unicode"=>'');
$icons['icomoon-brankic-32x32']['umbrella'] = array("class"=>'umbrella',"tags"=>'umbrella,rain,weather',"unicode"=>'');
$icons['icomoon-brankic-32x32']['streetlight'] = array("class"=>'streetlight',"tags"=>'street light,lights',"unicode"=>'');
$icons['icomoon-brankic-32x32']['bomb'] = array("class"=>'bomb',"tags"=>'bomb,destroy,blow up',"unicode"=>'');
$icons['icomoon-brankic-32x32']['archive'] = array("class"=>'archive',"tags"=>'archive',"unicode"=>'');
$icons['icomoon-brankic-32x32']['battery'] = array("class"=>'battery',"tags"=>'battery,full',"unicode"=>'');
$icons['icomoon-brankic-32x32']['battery2'] = array("class"=>'battery2',"tags"=>'battery',"unicode"=>'');
$icons['icomoon-brankic-32x32']['battery3'] = array("class"=>'battery3',"tags"=>'battery,low',"unicode"=>'');
$icons['icomoon-brankic-32x32']['battery4'] = array("class"=>'battery4',"tags"=>'battery,empty',"unicode"=>'');
$icons['icomoon-brankic-32x32']['battery5'] = array("class"=>'battery5',"tags"=>'battery',"unicode"=>'');
$icons['icomoon-brankic-32x32']['megaphone'] = array("class"=>'megaphone',"tags"=>'megaphone,advertise,notify,announce',"unicode"=>'');
$icons['icomoon-brankic-32x32']['megaphone2'] = array("class"=>'megaphone2',"tags"=>'megaphone,advertise,notify,announce',"unicode"=>'');
$icons['icomoon-brankic-32x32']['patch'] = array("class"=>'patch',"tags"=>'patch,fix',"unicode"=>'');
$icons['icomoon-brankic-32x32']['pil'] = array("class"=>'pil',"tags"=>'pil,drug,medicine',"unicode"=>'');
$icons['icomoon-brankic-32x32']['injection'] = array("class"=>'injection',"tags"=>'injection,medicine',"unicode"=>'');
$icons['icomoon-brankic-32x32']['thermometer'] = array("class"=>'thermometer',"tags"=>'thermometer,temprature',"unicode"=>'');
$icons['icomoon-brankic-32x32']['lamp3'] = array("class"=>'lamp3',"tags"=>'lamp,light',"unicode"=>'');
$icons['icomoon-brankic-32x32']['lamp4'] = array("class"=>'lamp4',"tags"=>'lamp,light',"unicode"=>'');
$icons['icomoon-brankic-32x32']['lamp5'] = array("class"=>'lamp5',"tags"=>'lamp,light',"unicode"=>'');
$icons['icomoon-brankic-32x32']['cube'] = array("class"=>'cube',"tags"=>'cube,3d,box',"unicode"=>'');
$icons['icomoon-brankic-32x32']['box'] = array("class"=>'box',"tags"=>'box,opened,package',"unicode"=>'');
$icons['icomoon-brankic-32x32']['box2'] = array("class"=>'box2',"tags"=>'box,package',"unicode"=>'');
$icons['icomoon-brankic-32x32']['diamond'] = array("class"=>'diamond',"tags"=>'diamond,gem',"unicode"=>'');
$icons['icomoon-brankic-32x32']['bag'] = array("class"=>'bag',"tags"=>'bag,sack,money',"unicode"=>'');
$icons['icomoon-brankic-32x32']['moneybag'] = array("class"=>'moneybag',"tags"=>'money bag,sack dollar,bag',"unicode"=>'');
$icons['icomoon-brankic-32x32']['grid'] = array("class"=>'grid',"tags"=>'grid,icons',"unicode"=>'');
$icons['icomoon-brankic-32x32']['grid2'] = array("class"=>'grid2',"tags"=>'grid,icons',"unicode"=>'');
$icons['icomoon-brankic-32x32']['list'] = array("class"=>'list',"tags"=>'list,menu,dropdown,options',"unicode"=>'');
$icons['icomoon-brankic-32x32']['list2'] = array("class"=>'list2',"tags"=>'list,menu',"unicode"=>'');
$icons['icomoon-brankic-32x32']['ruler'] = array("class"=>'ruler',"tags"=>'ruler,measure,length',"unicode"=>'');
$icons['icomoon-brankic-32x32']['ruler2'] = array("class"=>'ruler2',"tags"=>'ruler,measure,math',"unicode"=>'');
$icons['icomoon-brankic-32x32']['layout'] = array("class"=>'layout',"tags"=>'layout',"unicode"=>'');
$icons['icomoon-brankic-32x32']['layout2'] = array("class"=>'layout2',"tags"=>'layout',"unicode"=>'');
$icons['icomoon-brankic-32x32']['layout3'] = array("class"=>'layout3',"tags"=>'layout',"unicode"=>'');
$icons['icomoon-brankic-32x32']['layout4'] = array("class"=>'layout4',"tags"=>'layout',"unicode"=>'');
$icons['icomoon-brankic-32x32']['layout5'] = array("class"=>'layout5',"tags"=>'layout',"unicode"=>'');
$icons['icomoon-brankic-32x32']['layout6'] = array("class"=>'layout6',"tags"=>'layout',"unicode"=>'');
$icons['icomoon-brankic-32x32']['layout7'] = array("class"=>'layout7',"tags"=>'layout',"unicode"=>'');
$icons['icomoon-brankic-32x32']['layout8'] = array("class"=>'layout8',"tags"=>'layout',"unicode"=>'');
$icons['icomoon-brankic-32x32']['layout9'] = array("class"=>'layout9',"tags"=>'layout',"unicode"=>'');
$icons['icomoon-brankic-32x32']['layout10'] = array("class"=>'layout10',"tags"=>'layout',"unicode"=>'');
$icons['icomoon-brankic-32x32']['layout11'] = array("class"=>'layout11',"tags"=>'layout',"unicode"=>'');
$icons['icomoon-brankic-32x32']['layout12'] = array("class"=>'layout12',"tags"=>'layout',"unicode"=>'');
$icons['icomoon-brankic-32x32']['layout13'] = array("class"=>'layout13',"tags"=>'layout',"unicode"=>'');
$icons['icomoon-brankic-32x32']['layout14'] = array("class"=>'layout14',"tags"=>'layout',"unicode"=>'');
$icons['icomoon-brankic-32x32']['tools'] = array("class"=>'tools',"tags"=>'tools,options,repair',"unicode"=>'');
$icons['icomoon-brankic-32x32']['screwdriver'] = array("class"=>'screwdriver',"tags"=>'screwdriver,fix',"unicode"=>'');
$icons['icomoon-brankic-32x32']['paint'] = array("class"=>'paint',"tags"=>'paint,tool',"unicode"=>'');
$icons['icomoon-brankic-32x32']['hammer'] = array("class"=>'hammer',"tags"=>'hammer,tool,fix',"unicode"=>'');
$icons['icomoon-brankic-32x32']['brush'] = array("class"=>'brush',"tags"=>'brush,painting,art,drawing',"unicode"=>'');
$icons['icomoon-brankic-32x32']['pen'] = array("class"=>'pen',"tags"=>'pen,writing,blog',"unicode"=>'');
$icons['icomoon-brankic-32x32']['chat'] = array("class"=>'chat',"tags"=>'chat,comments,bubble,talk',"unicode"=>'');
$icons['icomoon-brankic-32x32']['comments'] = array("class"=>'comments',"tags"=>'comments,bubbles,chat,talk',"unicode"=>'');
$icons['icomoon-brankic-32x32']['chat2'] = array("class"=>'chat2',"tags"=>'chat,comment,talk',"unicode"=>'');
$icons['icomoon-brankic-32x32']['chat3'] = array("class"=>'chat3',"tags"=>'chat,comment,talk',"unicode"=>'');
$icons['icomoon-brankic-32x32']['volume'] = array("class"=>'volume',"tags"=>'volume,speaker,sound',"unicode"=>'');
$icons['icomoon-brankic-32x32']['volume2'] = array("class"=>'volume2',"tags"=>'volume,speaker,sound,loud',"unicode"=>'');
$icons['icomoon-brankic-32x32']['volume3'] = array("class"=>'volume3',"tags"=>'volume,speaker,mute',"unicode"=>'');
$icons['icomoon-brankic-32x32']['equalizer'] = array("class"=>'equalizer',"tags"=>'equalizer,settings,adjust',"unicode"=>'');
$icons['icomoon-brankic-32x32']['resize'] = array("class"=>'resize',"tags"=>'resize,responsive,maximize,enlarge',"unicode"=>'');
$icons['icomoon-brankic-32x32']['resize2'] = array("class"=>'resize2',"tags"=>'resize,shrink,collapse,contract',"unicode"=>'');
$icons['icomoon-brankic-32x32']['stretch'] = array("class"=>'stretch',"tags"=>'stretch,resize',"unicode"=>'');
$icons['icomoon-brankic-32x32']['narrow'] = array("class"=>'narrow',"tags"=>'narrow,resize',"unicode"=>'');
$icons['icomoon-brankic-32x32']['resize3'] = array("class"=>'resize3',"tags"=>'resize,maximize,enlarge',"unicode"=>'');
$icons['icomoon-brankic-32x32']['download3'] = array("class"=>'download3',"tags"=>'download,store,save',"unicode"=>'');
$icons['icomoon-brankic-32x32']['calculator'] = array("class"=>'calculator',"tags"=>'calculator,math,sum',"unicode"=>'');
$icons['icomoon-brankic-32x32']['library'] = array("class"=>'library',"tags"=>'library,university',"unicode"=>'');
$icons['icomoon-brankic-32x32']['auction'] = array("class"=>'auction',"tags"=>'auction,judge,rule,hammer,court',"unicode"=>'');
$icons['icomoon-brankic-32x32']['justice'] = array("class"=>'justice',"tags"=>'justice,balance,equality,court',"unicode"=>'');
$icons['icomoon-brankic-32x32']['stats'] = array("class"=>'stats',"tags"=>'stats,statistics,grow,increase,up',"unicode"=>'');
$icons['icomoon-brankic-32x32']['stats2'] = array("class"=>'stats2',"tags"=>'stats,statistics,decrease,down',"unicode"=>'');
$icons['icomoon-brankic-32x32']['attachment'] = array("class"=>'attachment',"tags"=>'attachment,paperclip',"unicode"=>'');
$icons['icomoon-brankic-32x32']['hourglass'] = array("class"=>'hourglass',"tags"=>'hourglass,timer,loading',"unicode"=>'');
$icons['icomoon-brankic-32x32']['abacus'] = array("class"=>'abacus',"tags"=>'abacus,calculate',"unicode"=>'');
$icons['icomoon-brankic-32x32']['pencil'] = array("class"=>'pencil',"tags"=>'pencil,write,writing,blog,edit',"unicode"=>'');
$icons['icomoon-brankic-32x32']['pen2'] = array("class"=>'pen2',"tags"=>'pen,writing,write,blog,edit',"unicode"=>'');
$icons['icomoon-brankic-32x32']['pin'] = array("class"=>'pin',"tags"=>'pin,location,map marker,marker',"unicode"=>'');
$icons['icomoon-brankic-32x32']['pin2'] = array("class"=>'pin2',"tags"=>'pin,location,map marker,marker',"unicode"=>'');
$icons['icomoon-brankic-32x32']['discout'] = array("class"=>'discout',"tags"=>'discout,price,sale,tag',"unicode"=>'');
$icons['icomoon-brankic-32x32']['edit'] = array("class"=>'edit',"tags"=>'edit,pencil,write,writing,save',"unicode"=>'');
$icons['icomoon-brankic-32x32']['scissors'] = array("class"=>'scissors',"tags"=>'scissors,cut',"unicode"=>'');
$icons['icomoon-brankic-32x32']['profile'] = array("class"=>'profile',"tags"=>'profile,card,id,vcard',"unicode"=>'');
$icons['icomoon-brankic-32x32']['profile2'] = array("class"=>'profile2',"tags"=>'profile,card,id,vcard',"unicode"=>'');
$icons['icomoon-brankic-32x32']['profile3'] = array("class"=>'profile3',"tags"=>'profile,card,id,vcard',"unicode"=>'');
$icons['icomoon-brankic-32x32']['rotate'] = array("class"=>'rotate',"tags"=>'rotate,ccw,reload,refresh,loop,arrow',"unicode"=>'');
$icons['icomoon-brankic-32x32']['rotate2'] = array("class"=>'rotate2',"tags"=>'rotate,cw,reload,refresh,loop,arrow',"unicode"=>'');
$icons['icomoon-brankic-32x32']['reply'] = array("class"=>'reply',"tags"=>'reply,arrow,left,undo',"unicode"=>'');
$icons['icomoon-brankic-32x32']['forward'] = array("class"=>'forward',"tags"=>'forward,arrow,right,redo',"unicode"=>'');
$icons['icomoon-brankic-32x32']['retweet'] = array("class"=>'retweet',"tags"=>'retweet,arrows,loop,reload',"unicode"=>'');
$icons['icomoon-brankic-32x32']['shuffle'] = array("class"=>'shuffle',"tags"=>'shuffle',"unicode"=>'');
$icons['icomoon-brankic-32x32']['loop'] = array("class"=>'loop',"tags"=>'loop',"unicode"=>'');
$icons['icomoon-brankic-32x32']['crop'] = array("class"=>'crop',"tags"=>'crop',"unicode"=>'');
$icons['icomoon-brankic-32x32']['square'] = array("class"=>'square',"tags"=>'square,path,vector',"unicode"=>'');
$icons['icomoon-brankic-32x32']['square2'] = array("class"=>'square2',"tags"=>'square,path,vector',"unicode"=>'');
$icons['icomoon-brankic-32x32']['circle'] = array("class"=>'circle',"tags"=>'circle,path,vector',"unicode"=>'');
$icons['icomoon-brankic-32x32']['dollar'] = array("class"=>'dollar',"tags"=>'dollar,bill,money',"unicode"=>'');
$icons['icomoon-brankic-32x32']['dollar2'] = array("class"=>'dollar2',"tags"=>'dollar,bill,money,stack',"unicode"=>'');
$icons['icomoon-brankic-32x32']['coins'] = array("class"=>'coins',"tags"=>'coins,money',"unicode"=>'');
$icons['icomoon-brankic-32x32']['pig'] = array("class"=>'pig',"tags"=>'pig,money,bank',"unicode"=>'');
$icons['icomoon-brankic-32x32']['bookmark'] = array("class"=>'bookmark',"tags"=>'bookmark,favorite,ribbon',"unicode"=>'');
$icons['icomoon-brankic-32x32']['bookmark2'] = array("class"=>'bookmark2',"tags"=>'bookmark,favorite,ribbon',"unicode"=>'');
$icons['icomoon-brankic-32x32']['addressbook'] = array("class"=>'addressbook',"tags"=>'address book,phone book,contacts',"unicode"=>'');
$icons['icomoon-brankic-32x32']['addressbook2'] = array("class"=>'addressbook2',"tags"=>'address book,phone book,contacts',"unicode"=>'');
$icons['icomoon-brankic-32x32']['safe'] = array("class"=>'safe',"tags"=>'safe,money',"unicode"=>'');
$icons['icomoon-brankic-32x32']['envelope'] = array("class"=>'envelope',"tags"=>'envelope,email,mail,letter,contact',"unicode"=>'');
$icons['icomoon-brankic-32x32']['envelope2'] = array("class"=>'envelope2',"tags"=>'envelope,email,mail,letter,contact',"unicode"=>'');
$icons['icomoon-brankic-32x32']['radioactive'] = array("class"=>'radioactive',"tags"=>'radio active,atomic',"unicode"=>'');
$icons['icomoon-brankic-32x32']['music'] = array("class"=>'music',"tags"=>'music,songs,sound',"unicode"=>'');
$icons['icomoon-brankic-32x32']['presentation'] = array("class"=>'presentation',"tags"=>'presentation,board,art board,chart',"unicode"=>'');
$icons['icomoon-brankic-32x32']['male'] = array("class"=>'male',"tags"=>'male,gender,man,sex',"unicode"=>'');
$icons['icomoon-brankic-32x32']['female'] = array("class"=>'female',"tags"=>'female,gender,sex,woman',"unicode"=>'');
$icons['icomoon-brankic-32x32']['aids'] = array("class"=>'aids',"tags"=>'aids',"unicode"=>'');
$icons['icomoon-brankic-32x32']['heart'] = array("class"=>'heart',"tags"=>'heart,love,like',"unicode"=>'');
$icons['icomoon-brankic-32x32']['info'] = array("class"=>'info',"tags"=>'info',"unicode"=>'');
$icons['icomoon-brankic-32x32']['info2'] = array("class"=>'info2',"tags"=>'info',"unicode"=>'');
$icons['icomoon-brankic-32x32']['piano'] = array("class"=>'piano',"tags"=>'piano,music',"unicode"=>'');
$icons['icomoon-brankic-32x32']['rain'] = array("class"=>'rain',"tags"=>'rain,weather,cloud',"unicode"=>'');
$icons['icomoon-brankic-32x32']['snow'] = array("class"=>'snow',"tags"=>'snow,cloud,weather',"unicode"=>'');
$icons['icomoon-brankic-32x32']['lightning'] = array("class"=>'lightning',"tags"=>'lightning,weather,cloud',"unicode"=>'');
$icons['icomoon-brankic-32x32']['sun'] = array("class"=>'sun',"tags"=>'sun,light,brightness,sunny,weather,day',"unicode"=>'');
$icons['icomoon-brankic-32x32']['moon'] = array("class"=>'moon',"tags"=>'moon,night',"unicode"=>'');
$icons['icomoon-brankic-32x32']['cloudy'] = array("class"=>'cloudy',"tags"=>'cloudy,weather',"unicode"=>'');
$icons['icomoon-brankic-32x32']['cloudy2'] = array("class"=>'cloudy2',"tags"=>'cloudy,weather',"unicode"=>'');
$icons['icomoon-brankic-32x32']['car'] = array("class"=>'car',"tags"=>'car,automobile,travel',"unicode"=>'');
$icons['icomoon-brankic-32x32']['bike'] = array("class"=>'bike',"tags"=>'bike,bicycle,travel,ride',"unicode"=>'');
$icons['icomoon-brankic-32x32']['truck'] = array("class"=>'truck',"tags"=>'truck,transfer,transmit,travel',"unicode"=>'');
$icons['icomoon-brankic-32x32']['bus'] = array("class"=>'bus',"tags"=>'bus,travel',"unicode"=>'');
$icons['icomoon-brankic-32x32']['bike2'] = array("class"=>'bike2',"tags"=>'bike,motorcycle,travel,ride',"unicode"=>'');
$icons['icomoon-brankic-32x32']['plane'] = array("class"=>'plane',"tags"=>'plane,fly,flight,airplane,travel',"unicode"=>'');
$icons['icomoon-brankic-32x32']['paperplane'] = array("class"=>'paperplane',"tags"=>'paper plane,travel,plane',"unicode"=>'');
$icons['icomoon-brankic-32x32']['rocket'] = array("class"=>'rocket',"tags"=>'rocket,jet,spaceship',"unicode"=>'');
$icons['icomoon-brankic-32x32']['book'] = array("class"=>'book',"tags"=>'book,reading',"unicode"=>'');
$icons['icomoon-brankic-32x32']['book2'] = array("class"=>'book2',"tags"=>'book,reading',"unicode"=>'');
$icons['icomoon-brankic-32x32']['barcode'] = array("class"=>'barcode',"tags"=>'barcode',"unicode"=>'');
$icons['icomoon-brankic-32x32']['barcode2'] = array("class"=>'barcode2',"tags"=>'barcode',"unicode"=>'');
$icons['icomoon-brankic-32x32']['expand'] = array("class"=>'expand',"tags"=>'expand,enlarge,full screen,maximize',"unicode"=>'');
$icons['icomoon-brankic-32x32']['collapse'] = array("class"=>'collapse',"tags"=>'collapse,shrink,minimize',"unicode"=>'');
$icons['icomoon-brankic-32x32']['popout'] = array("class"=>'popout',"tags"=>'pop out,pop up,out',"unicode"=>'');
$icons['icomoon-brankic-32x32']['popin'] = array("class"=>'popin',"tags"=>'pop in,embed',"unicode"=>'');
$icons['icomoon-brankic-32x32']['target'] = array("class"=>'target',"tags"=>'target',"unicode"=>'');
$icons['icomoon-brankic-32x32']['badge'] = array("class"=>'badge',"tags"=>'badge,sheriff',"unicode"=>'');
$icons['icomoon-brankic-32x32']['badge2'] = array("class"=>'badge2',"tags"=>'badge,sheriff',"unicode"=>'');
$icons['icomoon-brankic-32x32']['ticket'] = array("class"=>'ticket',"tags"=>'ticket,movies,theater',"unicode"=>'');
$icons['icomoon-brankic-32x32']['ticket2'] = array("class"=>'ticket2',"tags"=>'ticket,movies,theater',"unicode"=>'');
$icons['icomoon-brankic-32x32']['ticket3'] = array("class"=>'ticket3',"tags"=>'ticket,movies,theater',"unicode"=>'');
$icons['icomoon-brankic-32x32']['microphone4'] = array("class"=>'microphone4',"tags"=>'microphone,voice,record',"unicode"=>'');
$icons['icomoon-brankic-32x32']['cone'] = array("class"=>'cone',"tags"=>'cone,construction',"unicode"=>'');
$icons['icomoon-brankic-32x32']['blocked'] = array("class"=>'blocked',"tags"=>'blocked,forbidden,denied',"unicode"=>'');
$icons['icomoon-brankic-32x32']['stop'] = array("class"=>'stop',"tags"=>'stop',"unicode"=>'');
$icons['icomoon-brankic-32x32']['keyboard'] = array("class"=>'keyboard',"tags"=>'keyboard,type',"unicode"=>'');
$icons['icomoon-brankic-32x32']['keyboard2'] = array("class"=>'keyboard2',"tags"=>'keyboard,type',"unicode"=>'');
$icons['icomoon-brankic-32x32']['radio2'] = array("class"=>'radio2',"tags"=>'radio',"unicode"=>'');
$icons['icomoon-brankic-32x32']['printer'] = array("class"=>'printer',"tags"=>'printer',"unicode"=>'');
$icons['icomoon-brankic-32x32']['checked'] = array("class"=>'checked',"tags"=>'checked,checkmark,tick,checkbox',"unicode"=>'');
$icons['icomoon-brankic-32x32']['error'] = array("class"=>'error',"tags"=>'error,cancel,close,partially checked',"unicode"=>'');
$icons['icomoon-brankic-32x32']['add'] = array("class"=>'add',"tags"=>'add,plus',"unicode"=>'');
$icons['icomoon-brankic-32x32']['minus3'] = array("class"=>'minus3',"tags"=>'minus,remove,delete',"unicode"=>'');
$icons['icomoon-brankic-32x32']['alert'] = array("class"=>'alert',"tags"=>'alert,warning,exclamation',"unicode"=>'');
$icons['icomoon-brankic-32x32']['pictures3'] = array("class"=>'pictures3',"tags"=>'pictures,images,photos',"unicode"=>'');
$icons['icomoon-brankic-32x32']['atom'] = array("class"=>'atom',"tags"=>'atom,nuclear',"unicode"=>'');
$icons['icomoon-brankic-32x32']['eyedropper'] = array("class"=>'eyedropper',"tags"=>'eyedropper,color,drop',"unicode"=>'');
$icons['icomoon-brankic-32x32']['globe'] = array("class"=>'globe',"tags"=>'globe,network,sphere',"unicode"=>'');
$icons['icomoon-brankic-32x32']['globe2'] = array("class"=>'globe2',"tags"=>'globe,network,sphere',"unicode"=>'');
$icons['icomoon-brankic-32x32']['shipping'] = array("class"=>'shipping',"tags"=>'shipping',"unicode"=>'');
$icons['icomoon-brankic-32x32']['yingyang'] = array("class"=>'yingyang',"tags"=>'ying yang',"unicode"=>'');
$icons['icomoon-brankic-32x32']['compass'] = array("class"=>'compass',"tags"=>'compass,location,direction',"unicode"=>'');
$icons['icomoon-brankic-32x32']['zip'] = array("class"=>'zip',"tags"=>'zip,compress,file',"unicode"=>'');
$icons['icomoon-brankic-32x32']['zip2'] = array("class"=>'zip2',"tags"=>'zip,compress,file',"unicode"=>'');
$icons['icomoon-brankic-32x32']['anchor'] = array("class"=>'anchor',"tags"=>'anchor,link,reference',"unicode"=>'');
$icons['icomoon-brankic-32x32']['lockedheart'] = array("class"=>'lockedheart',"tags"=>'locked heart,heart,lock',"unicode"=>'');
$icons['icomoon-brankic-32x32']['magnet'] = array("class"=>'magnet',"tags"=>'magnet,attract',"unicode"=>'');
$icons['icomoon-brankic-32x32']['navigation'] = array("class"=>'navigation',"tags"=>'navigation,nautical vessel,vessel,wheel',"unicode"=>'');
$icons['icomoon-brankic-32x32']['tags'] = array("class"=>'tags',"tags"=>'tags,prices',"unicode"=>'');
$icons['icomoon-brankic-32x32']['heart2'] = array("class"=>'heart2',"tags"=>'heart,plus,add,love,like',"unicode"=>'');
$icons['icomoon-brankic-32x32']['heart3'] = array("class"=>'heart3',"tags"=>'heart,minus,remove,love,like,delete',"unicode"=>'');
$icons['icomoon-brankic-32x32']['usb'] = array("class"=>'usb',"tags"=>'usb,flash,drive',"unicode"=>'');
$icons['icomoon-brankic-32x32']['clipboard'] = array("class"=>'clipboard',"tags"=>'clipboard,list,board',"unicode"=>'');
$icons['icomoon-brankic-32x32']['clipboard2'] = array("class"=>'clipboard2',"tags"=>'clipboard',"unicode"=>'');
$icons['icomoon-brankic-32x32']['clipboard3'] = array("class"=>'clipboard3',"tags"=>'clipboard,list,board',"unicode"=>'');
$icons['icomoon-brankic-32x32']['switch2'] = array("class"=>'switch2',"tags"=>'switch,power',"unicode"=>'');
$icons['icomoon-brankic-32x32']['ruler3'] = array("class"=>'ruler3',"tags"=>'ruler,pencil,design',"unicode"=>'');